[platformio]
default_envs = Firmware_Gateway_Sensor_Arroz

; ==========================================
; FIRMWARE NORMAL
; ==========================================
[env:Firmware_Gateway_Sensor_Arroz]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_src_filter =
    +<*>
    -<calibration_mode/>

build_flags =
    -I src/data_model
    -I src/lora_mesh
    -I src/rssi_handler
    -I src/sensor_processing
    -I src/web_server
    -I src/wifi_manager

lib_deps =
    https://github.com/lacamera/ESPAsyncWebServer
    https://github.com/dvarrel/AsyncTCP
    https://github.com/arduino-libraries/Arduino_JSON
    WiFi
    SPIFFS

; ==========================================
; FIRMWARE DE CALIBRAÇÃO
; Exclui tudo exceto calibration_mode/
; Não toca no firmware normal.
; ==========================================
[env:calibration]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_src_filter =
    +<*>16551925
    -<main.cpp>
    -<web_server/>
    -<wifi_manager/>
    -<rssi_handler/>
    -<data_model/>
    -<sensor_processing/>
    -<lora_mesh/>

lib_deps =
    SPIFFS